export { default as Home } from './home'
export { default as Archive } from './archive'
export { default as Favorite } from './favorite'
export { default as Login } from './login'
export { default as Register } from './register'
